# Generated by Django 6.0.3 on 2026-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_question_choice_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(null=True, to='onlinecourse.instructor'),
        ),
    ]
